In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
a=2
b=2
c=3
ab=4

In [3]:
a+b

4

In [4]:
a+b==ab

True

In [5]:
print(a)

2


In [6]:
print(a,b)

2 2


In [7]:
a/c

0.6666666666666666

In [8]:
a/b

1.0

In [9]:
a+b*c

8

In [10]:
a+(b*c)

8

In [11]:
ab>c

True

In [12]:
round(a/c)

1

In [13]:
text = "Text"

In [14]:
print(text)

Text


In [15]:
big_text=text+text

In [16]:
print(big_text)

TextText


In [17]:
text_formating = f"{a}+{b}={ab}"

In [18]:
print(text_formating)

2+2=4


In [19]:
number_formating = "%.2f" % (a/c)

In [20]:
print(number_formating)

0.67


In [21]:
number_formating = f"{(a/c):.{2}}"

In [22]:
print(number_formating)

0.67


In [23]:
items = [1, 2, 3, 5, 6, 7]

In [24]:
first = items[0]
first

1

In [25]:
last = items[-1]
last

7

In [26]:
first_two = items[0:2]
first_two


[1, 2]

In [27]:
skip_two = items[2:]
skip_two

[3, 5, 6, 7]

In [28]:
concatenation = items + items
concatenation

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [29]:
[i for i in items]

[1, 2, 3, 5, 6, 7]

In [30]:
[2*i for i in items]

[2, 4, 6, 10, 12, 14]

In [31]:
nested_list = [items for i in items]
nested_list

[[1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7]]

In [32]:
flattened_list = [k for n in nested_list for k in n]
flattened_list

[1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7]

In [33]:
conditional = [n for n in items if n%2==0]
conditional

[2, 6]

In [34]:
10*[1]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [35]:
data = []
for v,i in enumerate(10*[1]):
    data.append(v*i)
    
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
dictionary = {"banana":"apple", "pear":"strawbery"}

In [37]:
dictionary["banana"]

'apple'

In [38]:
for k,v in dictionary.items():
    print(f"{k}:{v}")

banana:apple
pear:strawbery


In [39]:
c = True

if c:
    print("kek")
else:
    print("nope")

kek


In [40]:
c = "That will be true also"

if c:
    print("kek")
else:
    print("nope")

kek


In [41]:
c = None

if c:
    print("kek")
else:
    print("nope")

nope


In [42]:
c = 0

if c:
    print("kek")
else:
    print("nope")

nope


In [43]:
def function(param):
    print(param)
    
function("kek")

kek


In [44]:
lambda_expression = lambda x: print(x)

lambda_expression("kek2")

kek2


In [45]:
def lambda_as_param(expression):
    print(expression("kek"))

lambda_as_param(lambda x: f"HeHe {x}")

HeHe kek


In [46]:
class SimpleClass:
    
    def __init__(self):
        print("Constructor")
        
instance=SimpleClass()

Constructor


In [47]:
class SimpleClass2:
    
    def __init__(self, param):
        self.param=param
    
    def function(self):
        print(self.param)
        
    def function_with_param(self, param):
        print(param)
        
        
instance=SimpleClass2("kek")

instance.function()
instance.function_with_param("kek2")

kek
kek2


In [48]:
class SimpleClass3:
    
    @staticmethod
    def function():
        print("staticcccc")

SimpleClass3.function()

staticcccc


In [49]:
class Base:
    
    def method(self):
        print("base method")
        
class Inheritance(Base):
    def child_method(self):
        print("Child")

instance=Inheritance()
instance.method()
instance.child_method()

base method
Child


In [50]:
class Base:
    
    def __init__(self, param):
        self.param=param
        
class Inheritance(Base):
    def __init__(self):
        super(Inheritance, self).__init__("kek")

instance=Inheritance()
instance.param

'kek'

In [51]:
import numpy as np

In [52]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.zeros((3,4)) 

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [54]:
np.ones((3,4)) 

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [55]:
np.eye(3) 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [56]:
a.shape 

(2, 3)

In [57]:
len(a)

2

In [58]:
a-a

array([[0, 0, 0],
       [0, 0, 0]])

In [59]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
a/a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [61]:
a*10

array([[10, 20, 30],
       [40, 50, 60]])

In [62]:
a/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [63]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
np.dot(a,np.transpose(a))

array([[14, 32],
       [32, 77]])

In [65]:
np.log(a)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947]])

In [66]:
a.max()

6

In [67]:
a.min()

1

In [68]:
a.mean()

3.5

In [69]:
a.std()

1.707825127659933

In [70]:
a==a

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [71]:
b=np.array([1,2,3])
c=np.array([[1],[2],[3]])

In [72]:
b

array([1, 2, 3])

In [73]:
c

array([[1],
       [2],
       [3]])

In [74]:
b*c

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])