In [221]:
import this

In [222]:
a=2
b=2
c=3
ab=4

In [223]:
a+b

4

In [224]:
a+b==ab

True

In [225]:
print(a)

2


In [226]:
print(a,b)

2 2


In [227]:
a/c

0.6666666666666666

In [228]:
a/b

1.0

In [229]:
a+b*c

8

In [230]:
a+(b*c)

8

In [231]:
ab>c

True

In [232]:
round(a/c)

1

In [233]:
text = "Text"

In [234]:
print(text)

Text


In [235]:
big_text=text+text

In [236]:
print(big_text)

TextText


In [237]:
text_formating = f"{a}+{b}={ab}"

In [238]:
print(text_formating)

2+2=4


In [239]:
number_formating = "%.2f" % (a/c)

In [240]:
print(number_formating)

0.67


In [241]:
number_formating = f"{(a/c):.{2}}"

In [242]:
print(number_formating)

0.67


In [243]:
items = [1, 2, 3, 5, 6, 7]

In [244]:
first = items[0]
first

1

In [245]:
last = items[-1]
last

7

In [246]:
first_two = items[0:2]
first_two


[1, 2]

In [247]:
skip_two = items[2:]
skip_two

[3, 5, 6, 7]

In [248]:
concatenation = items + items
concatenation

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [249]:
[i for i in items]

[1, 2, 3, 5, 6, 7]

In [250]:
[2*i for i in items]

[2, 4, 6, 10, 12, 14]

In [251]:
nested_list = [items for i in items]
nested_list

[[1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7],
 [1, 2, 3, 5, 6, 7]]

In [252]:
flattened_list = [k for n in nested_list for k in n]
flattened_list

[1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7,
 1,
 2,
 3,
 5,
 6,
 7]

In [253]:
conditional = [n for n in items if n%2==0]
conditional

[2, 6]

In [254]:
10*[1]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [255]:
data = []
for v,i in enumerate(10*[1]):
    data.append(v*i)
    
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [256]:
dictionary = {"banana":"apple", "pear":"strawbery"}

In [257]:
dictionary["banana"]

'apple'

In [258]:
for k,v in dictionary.items():
    print(f"{k}:{v}")

banana:apple
pear:strawbery


In [259]:
def function(param):
    print(param)
    
function("kek")

kek


In [260]:
lambda_expression = lambda x: print(x)

lambda_expression("kek2")

kek2


In [261]:
def lambda_as_param(expression):
    print(expression("kek"))

lambda_as_param(lambda x: f"HeHe {x}")

HeHe kek


In [262]:
class SimpleClass:
    
    def __init__(self):
        print("Constructor")
        
instance=SimpleClass()

Constructor


In [263]:
class SimpleClass2:
    
    def __init__(self, param):
        self.param=param
    
    def function(self):
        print(self.param)
        
    def function_with_param(self, param):
        print(param)
        
        
instance=SimpleClass2("kek")

instance.function()
instance.function_with_param("kek2")

kek
kek2


In [264]:
class SimpleClass3:
    
    @staticmethod
    def function():
        print("staticcccc")

SimpleClass3.function()

staticcccc


In [265]:
class Base:
    
    def method(self):
        print("base method")
        
class Inheritance(Base):
    def child_method(self):
        print("Child")

instance=Inheritance()
instance.method()
instance.child_method()

base method
Child


In [266]:
class Base:
    
    def __init__(self, param):
        self.param=param
        
class Inheritance(Base):
    def __init__(self):
        super(Inheritance, self).__init__("kek")

instance=Inheritance()
instance.param

'kek'

In [267]:
import numpy as np

In [268]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [269]:
np.zeros((3,4)) 

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [270]:
np.ones((3,4)) 

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [271]:
np.eye(3) 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [272]:
a.shape 

(2, 3)

In [273]:
len(a)

2

In [274]:
a-a

array([[0, 0, 0],
       [0, 0, 0]])

In [275]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [276]:
a/a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [277]:
a*10

array([[10, 20, 30],
       [40, 50, 60]])

In [278]:
a/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [279]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [280]:
np.dot(a,np.transpose(a))

array([[14, 32],
       [32, 77]])

In [281]:
np.log(a)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947]])

In [282]:
a.max()

6

In [283]:
a.min()

1

In [284]:
a.mean()

3.5

In [285]:
a.std()

1.707825127659933

In [286]:
a==a

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [287]:
b=np.array([1,2,3])
c=np.array([[1],[2],[3]])

In [288]:
b

array([1, 2, 3])

In [289]:
c

array([[1],
       [2],
       [3]])

In [290]:
b*c

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])